---
- name: create database
  become_user: "postgres"
  postgresql_db:
    name: "{{ db_name }}"

- name: create database user
  become_user: "postgres"
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_user_passwd }}"
    priv: ALL
