---
- name: install requirements.txt
  pip:
    virtualenv: "{{ project_virtualenv_dir }}"
    virtualenv_python: python3.6
    requirements: "{{ project_work_tree }}/requirements.txt"
  notify:
    - restart gunicorn
    - restart gunicorn socket

- name: copy settings config
  template: src=settings.j2 dest={{ project_work_tree }}/src/{{ project_namespace }}/{{ env_name }}_settings.py
  notify:
    - restart gunicorn
    - restart gunicorn socket

- name: migrate
  command: "{{ project_virtualenv_dir }}/bin/python {{ project_work_tree }}/src/manage.py migrate --noinput"
  notify:
    - restart gunicorn
    - restart gunicorn socket

- name: collectstatic
  command: "{{ project_virtualenv_dir }}/bin/python {{ project_work_tree }}/src/manage.py collectstatic --noinput"
