# Generated by Django 2.0.7 on 2018-07-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20180711_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='translate',
            new_name='translation',
        ),
    ]
