# Generated by Django 2.0.7 on 2018-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20180711_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='example',
            field=models.TextField(blank=True),
        ),
    ]
