# Generated by Django 2.0.7 on 2018-07-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_definition_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='need_clarify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='words.Word'),
        ),
    ]
