# Generated by Django 2.0.7 on 2018-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_auto_20180711_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
