# Generated by Django 2.0.7 on 2018-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_auto_20180812_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='meaning',
            field=models.CharField(max_length=255),
        ),
    ]
