# Generated by Django 2.0.7 on 2018-08-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_auto_20180812_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='translate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='example',
            name='translate',
            field=models.TextField(blank=True),
        ),
    ]
