# Generated by Django 2.0.7 on 2018-08-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0014_auto_20180812_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='association_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
